baseURL = 'https://haruayakaji.github.io/'
defaultContentLanguage = 'zh-tw'
defaultContentLanguageInSubdir = true
relativeURLs = true
theme = 'hugo-theme-relearn'
title = 'å°é‡å¯ºæ˜¥'

[params]
author.name = 'HaruAyakaji'
breadcrumbSeparator = 'ï¹¥'
disableExplicitIndexURLs = true
disableInlineCopyToClipBoard = true
disableLandingPageButton = true
disableShortcutsTitle = true
highlightWrap = false
imageEffects.lightbox = false
themeVariant = 'relearn-dark'

[outputs]
home = ['html', 'rss', 'search', 'searchpage']

[languages]
[languages.zh-tw]
contentDir = 'content/zh-tw'
languageCode = 'zh-Hant-TW'
languageName = 'ğŸ‡¹ğŸ‡¼ ç¹é«”ä¸­æ–‡ (å°ç£)'
params.description = 'å°é‡å¯ºæ˜¥çš„ç¨‹å¼è¨­è¨ˆå­¸ç¿’ç­†è¨˜'
weight = 1

[languages.ja]
contentDir = 'content/ja'
languageCode = 'ja'
languageName = 'ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª (æ—¥æœ¬)'
params.description = 'å°é‡å¯ºæ˜¥ã®ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°å­¦ç¿’ãƒãƒ¼ãƒˆ'
weight = 2
